#!/bin/bash
#@ class            = clallmds
#@ job_name         = smilei
#@ total_tasks      = 2
#@ node             = 1
#@ node_usage       = not_shared
#@ wall_clock_limit = 00:30:00
#@ output           = smilei.out
#@ error            = smilei.err
#@ job_type         = mpich
#@ environment      = COPY_ALL
#@ queue

# Remove existing outputs
rm *.h5

# Some OpenMP parameters
export OMP_NUM_THREADS=8
export OMP_SCHEDULE=dynamic
export OMP_PROC_BIND=true

# We run the case
mpirun -np 2 ./smilei thermal_plasma_1d.py

